notifications:
  email:
    - dean@airdb.com
dist: trusty
sudo: required

language: node_js
node_js:
  "node"
cache:
  directories:
    "node_modules"
env:
  WechatMSG="https://aws.airdb.io/wechat/sendmsg"
  TARVIS_URL="https://travis-ci.org/$TRAVIS_REPO_SLUG/builds/$TRAVIS_BUILD_ID#$TRAVIS_BUILD_NUMBER"
  RELEASE_URL="https://www.airdb.com/website/dist_${TRAVIS_COMMIT}/index.html"

# cache components
before_install:
    - which npm
    - npm install -g @vue/cli
install:
    - ls -l
before_script:
    - echo "before_script"
script:
    - npm install
    - npm run build
