name: Deploy Docs

on: [push]

jobs:
  deploy-gh-pages:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Build Docs
        env:
          NODE_OPTIONS: --max_old_space_size=4096
        run: |
          make build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUBBOTTOKEN }}
          publish_branch: gh-pages
          publish_dir: docs/.vuepress/dist
